BOOKS = [
    {"id": 1, "title": "The Great Gatsby", "author": "F. Scott Fitzgerald"},
    {"id": 2, "title": "1984", "author": "George Orwell"},
    {"id": 3, "title": "Animal Farm", "author": "George Orwell"},
    {"id": 4, "title": "Nineteen Eighty-Four", "author": "George Orwell"},
    {"id": 5, "title": "Homage to Catalonia", "author": "George Orwell"},
    {"id": 6, "title": "To Kill a Mockingbird", "author": "Harper Lee"},
    {"id": 7, "title": "Pride and Prejudice", "author": "Jane Austen"},
    {"id": 8, "title": "Jane Eyre", "author": "Charlotte Brontë"},
    {"id": 9, "title": "Moby-Dick", "author": "Herman Melville"},
    {"id": 10, "title": "The Catcher in the Rye", "author": "J.D. Salinger"},
    {"id": 11, "title": "Brave New World", "author": "Aldous Huxley"},
    {"id": 12, "title": "The Lord of the Rings", "author": "J.R.R. Tolkien"},
    {"id": 13, "title": "The Hobbit", "author": "J.R.R. Tolkien"},
    {"id": 14, "title": "Fahrenheit 451", "author": "Ray Bradbury"},
    {"id": 15, "title": "The Picture of Dorian Gray", "author": "Oscar Wilde"},
    {"id": 16, "title": "Dracula", "author": "Bram Stoker"},
    {"id": 17, "title": "Frankenstein", "author": "Mary Shelley"},
    {"id": 18, "title": "The Odyssey", "author": "Homer"},
    {"id": 19, "title": "The Brothers Karamazov", "author": "Fyodor Dostoevsky"},
    {"id": 20, "title": "Crime and Punishment", "author": "Fyodor Dostoevsky"},
    {"id": 21, "title": "War and Peace", "author": "Leo Tolstoy"},
    {"id": 22, "title": "One Hundred Years of Solitude", "author": "Gabriel García Márquez"},
    {"id": 23, "title": "The Count of Monte Cristo", "author": "Alexandre Dumas"},
    {"id": 24, "title": "The Little Prince", "author": "Antoine de Saint-Exupéry"},
    {"id": 25, "title": "The Grapes of Wrath", "author": "John Steinbeck"},
    {"id": 26, "title": "The Adventures of Huckleberry Finn", "author": "Mark Twain"},
    {"id": 27, "title": "Gone with the Wind", "author": "Margaret Mitchell"},
    {"id": 28, "title": "A Tale of Two Cities", "author": "Charles Dickens"},
    {"id": 29, "title": "The Great Expectations", "author": "Charles Dickens"},
    {"id": 30, "title": "The Adventures of Sherlock Holmes", "author": "Arthur Conan Doyle"},
    {"id": 31, "title": "Pride and Prejudice", "author": "Jane Austen"},
    {"id": 32, "title": "Wuthering Heights", "author": "Emily Brontë"},
    {"id": 33, "title": "The Divine Comedy", "author": "Dante Alighieri"},
    {"id": 34, "title": "Heart of Darkness", "author": "Joseph Conrad"},
    {"id": 35, "title": "The Stranger", "author": "Albert Camus"},
    {"id": 36, "title": "Anna Karenina", "author": "Leo Tolstoy"},
    {"id": 37, "title": "Les Misérables", "author": "Victor Hugo"},
    {"id": 38, "title": "The Old Man and the Sea", "author": "Ernest Hemingway"},
    {"id": 39, "title": "Slaughterhouse-Five", "author": "Kurt Vonnegut"},
    {"id": 40, "title": "Catch-22", "author": "Joseph Heller"},
    {"id": 41, "title": "The Hobbit", "author": "J.R.R. Tolkien"},
    {"id": 42, "title": "The Lord of the Rings", "author": "J.R.R. Tolkien"},
    {"id": 43, "title": "The Shining", "author": "Stephen King"},
    {"id": 44, "title": "The Stand", "author": "Stephen King"},
    {"id": 45, "title": "The Name of the Rose", "author": "Umberto Eco"},
    {"id": 46, "title": "The Road", "author": "Cormac McCarthy"},
    {"id": 47, "title": "The Call of the Wild", "author": "Jack London"},
    {"id": 48, "title": "White Fang", "author": "Jack London"},
    {"id": 49, "title": "The Time Machine", "author": "H.G. Wells"},
    {"id": 50, "title": "A Clockwork Orange", "author": "Anthony Burgess"},
    {"id": 51, "title": "The Book Thief", "author": "Markus Zusak"},
    {"id": 52, "title": "The Giver", "author": "Lois Lowry"},
    {"id": 53, "title": "The Road", "author": "Cormac McCarthy"},
    {"id": 54, "title": "The Name of the Rose", "author": "Umberto Eco"},
    {"id": 55, "title": "The Hunger Games", "author": "Suzanne Collins"},
    {"id": 56, "title": "Catching Fire", "author": "Suzanne Collins"},
    {"id": 57, "title": "Mockingjay", "author": "Suzanne Collins"},
    {"id": 58, "title": "The Maze Runner", "author": "James Dashner"},
    {"id": 59, "title": "The Scorch Trials", "author": "James Dashner"},
    {"id": 60, "title": "The Death Cure", "author": "James Dashner"},
    {"id": 61, "title": "Divergent", "author": "Veronica Roth"},
    {"id": 62, "title": "Insurgent", "author": "Veronica Roth"},
    {"id": 63, "title": "Allegiant", "author": "Veronica Roth"},
    {"id": 64, "title": "The Da Vinci Code", "author": "Dan Brown"},
    {"id": 65, "title": "Angels & Demons", "author": "Dan Brown"},
    {"id": 66, "title": "Inferno", "author": "Dan Brown"},
    {"id": 67, "title": "The Alchemist", "author": "Paulo Coelho"},
    {"id": 68, "title": "Brida", "author": "Paulo Coelho"},
    {"id": 69, "title": "Veronika Decides to Die", "author": "Paulo Coelho"},
    {"id": 70, "title": "The Girl with the Dragon Tattoo", "author": "Stieg Larsson"},
    {"id": 71, "title": "The Girl Who Played with Fire", "author": "Stieg Larsson"},
    {"id": 72, "title": "The Girl Who Kicked the Hornet's Nest", "author": "Stieg Larsson"},
    {"id": 73, "title": "The Help", "author": "Kathryn Stockett"},
    {"id": 74, "title": "The Girl on the Train", "author": "Paula Hawkins"},
    {"id": 75, "title": "Gone Girl", "author": "Gillian Flynn"},
    {"id": 76, "title": "Big Little Lies", "author": "Liane Moriarty"},
    {"id": 77, "title": "The Night Circus", "author": "Erin Morgenstern"},
    {"id": 78, "title": "A Game of Thrones", "author": "George R.R. Martin"},
    {"id": 79, "title": "A Clash of Kings", "author": "George R.R. Martin"},
    {"id": 80, "title": "A Storm of Swords", "author": "George R.R. Martin"},
    {"id": 81, "title": "A Feast for Crows", "author": "George R.R. Martin"},
    {"id": 82, "title": "A Dance with Dragons", "author": "George R.R. Martin"},
    {"id": 83, "title": "The Fellowship of the Ring", "author": "J.R.R. Tolkien"},
    {"id": 84, "title": "The Two Towers", "author": "J.R.R. Tolkien"},
    {"id": 85, "title": "The Return of the King", "author": "J.R.R. Tolkien"},
    {"id": 86, "title": "Harry Potter and the Sorcerer's Stone", "author": "J.K. Rowling"},
    {"id": 87, "title": "Harry Potter and the Chamber of Secrets", "author": "J.K. Rowling"},
    {"id": 88, "title": "Harry Potter and the Prisoner of Azkaban", "author": "J.K. Rowling"},
    {"id": 89, "title": "Harry Potter and the Goblet of Fire", "author": "J.K. Rowling"},
    {"id": 90, "title": "Harry Potter and the Order of the Phoenix", "author": "J.K. Rowling"},
    {"id": 91, "title": "Harry Potter and the Half-Blood Prince", "author": "J.K. Rowling"},
    {"id": 92, "title": "Harry Potter and the Deathly Hallows", "author": "J.K. Rowling"},
    {"id": 93, "title": "The Chronicles of Narnia: The Lion, the Witch, and the Wardrobe", "author": "C.S. Lewis"},
    {"id": 94, "title": "The Chronicles of Narnia: Prince Caspian", "author": "C.S. Lewis"},
    {"id": 95, "title": "The Chronicles of Narnia: The Voyage of the Dawn Treader", "author": "C.S. Lewis"},
    {"id": 96, "title": "The Chronicles of Narnia: The Silver Chair", "author": "C.S. Lewis"},
    {"id": 97, "title": "The Chronicles of Narnia: The Horse and His Boy", "author": "C.S. Lewis"},
    {"id": 98, "title": "The Chronicles of Narnia: The Magician's Nephew", "author": "C.S. Lewis"},
    {"id": 99, "title": "The Chronicles of Narnia: The Last Battle", "author": "C.S. Lewis"},
    {"id": 100, "title": "Lord of the Flies", "author": "William Golding"}
]
